title: Project
files: true
pages: false
files:
  fields:
    color0:
      label: Dominant Color 1
      type: color
    color1:
      label: Dominant Color 2
      type: color
    duo:
      label: Merge with next image ?
      type: toggle
      default: no
    videolink:
      label: Video ID
      type: text
      icon: code
      help: Youtube ID or Vimeo ID
    vendor:
      label: Vendor
      type: radio
      default: vimeo
      options:
        vimeo: Vimeo 
        youtube: Youtube
    videoexternal:
      label: Video external file link
      type: url
    videofile:
      label: Video File
      type: select
      options: videos
fields:
  prevnext: prevnext
  title:
    label: Title
    type:  text
    width: 1/3
  subtitle:
    label: Subtitle
    type: text
    width: 1/3
  category:
    label: Category
    type: select
    required: true
    options:
      commissioned: Commissioned
      personal: Personal
    width: 1/3
  featured:
    label: Featured image
    type: quickselect
    options: images
    help: Required to display project
    width: 1/4
  size:
    label: Size
    type: select
    width: 1/4
    columns: 1
    default: small
    required: true
    options:
      small: Small
      medium: Medium
      large: Large
  marginLeft:
    label: Offset Left
    type: number
    step: 1
    min: 0
    max: 8
    default: 0
    width: 1/4
  marginRight:
    label: Offset Right
    type: number
    step: 1
    min: 0
    max: 8
    default: 0
    width: 1/4
  medias: 
    label: Images
    type: images
  text:
    label: Description (SEO)
    type: textarea
    help: For search engines
